# Generated by Django 5.2 on 2025-05-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_pdfsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfsummary",
            name="title",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
