# Generated by Django 5.2 on 2025-05-01 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_pdfsummary_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfsummary",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
