# Generated by Django 5.2 on 2025-05-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userprofile"),
    ]

    operations = []
